import { Component, OnInit, AfterViewInit } from '@angular/core';
import {
  Chart,
  DoughnutController,
  ArcElement,
  Tooltip,
  Legend,
  Title
} from 'chart.js';

Chart.register(
  DoughnutController,
  ArcElement,
  Tooltip,
  Legend,
  Title
);

@Component({
  selector: 'app-audit-reports',
  templateUrl: './audit-reports.component.html',
  styleUrls: ['./audit-reports.component.css']
})
export class AuditReportsComponent implements OnInit, AfterViewInit {

  // ======================================
  // Filter Variables
  // ======================================

  dateRange = '';
  selectedType = 'All Types';
  selectedStatus = 'All Status';
  generatedBy = 'All Users';
  searchText = '';

  filteredReports: any[] = [];

  constructor() {}



  ngAfterViewInit(): void {
    this.createReportTypeChart();
    this.createStatusChart();
  }

  // ======================================
  // KPI Cards
  // ======================================

  stats = [

    {
      icon: 'bi-file-earmark-text',
      color: 'primary',
      title: 'Total Reports',
      value: '156',
      subtitle: 'All generated reports'
    },

    {
      icon: 'bi-clipboard-check',
      color: 'success',
      title: 'Generated',
      value: '18',
      subtitle: '+12% this month'
    },

    {
      icon: 'bi-download',
      color: 'warning',
      title: 'Downloads',
      value: '245',
      subtitle: 'Total downloads'
    },

    {
      icon: 'bi-exclamation-circle',
      color: 'danger',
      title: 'Failed',
      value: '3',
      subtitle: 'Requires attention'
    },

    {
      icon: 'bi-hdd-stack',
      color: 'purple',
      title: 'Storage',
      value: '245 MB',
      subtitle: 'Storage consumed'
    }

  ];
    // ======================================
  // Recent Activities
  // ======================================

  recentActivities = [

    {
      icon: 'bi-check-circle-fill',
      title: 'Reconciliation Summary',
      subtitle: 'Generated by Admin',
      time: '2 mins ago'
    },

    {
      icon: 'bi-file-earmark-check',
      title: 'Audit Trail',
      subtitle: 'Generated by Finance',
      time: '15 mins ago'
    },

    {
      icon: 'bi-download',
      title: 'Downloaded Report',
      subtitle: 'User: John',
      time: '30 mins ago'
    },

    {
      icon: 'bi-clock-history',
      title: 'Monthly Report',
      subtitle: 'Scheduled Report',
      time: '1 hour ago'
    },

    {
      icon: 'bi-shield-check',
      title: 'Compliance Report',
      subtitle: 'Completed Successfully',
      time: 'Today'
    }

  ];

  // ======================================
  // Reports Table
  // ======================================

  reports = [

    {
      name: 'Bank Reconciliation Summary',
      type: 'Reconciliation',
      range: '01 Jul - 15 Jul',
      generatedOn: '16 Jul 2026',
      user: 'Admin',
      status: 'Completed',
      badge: 'bg-success-subtle text-success',
      size: '2.3 MB'
    },

    {
      name: 'Discrepancy Report',
      type: 'Exception',
      range: '01 Jul - 15 Jul',
      generatedOn: '16 Jul 2026',
      user: 'Finance',
      status: 'Completed',
      badge: 'bg-success-subtle text-success',
      size: '1.8 MB'
    },

    {
      name: 'Audit Trail',
      type: 'Audit',
      range: 'June',
      generatedOn: '15 Jul 2026',
      user: 'System',
      status: 'In Progress',
      badge: 'bg-warning-subtle text-warning',
      size: '--'
    },

    {
      name: 'Transaction Details',
      type: 'Transaction',
      range: '01 Jul - 10 Jul',
      generatedOn: '14 Jul 2026',
      user: 'Admin',
      status: 'Failed',
      badge: 'bg-danger-subtle text-danger',
      size: '--'
    },

    {
      name: 'Compliance Report',
      type: 'Compliance',
      range: 'July',
      generatedOn: '13 Jul 2026',
      user: 'Auditor',
      status: 'Completed',
      badge: 'bg-success-subtle text-success',
      size: '3.5 MB'
    },

    {
      name: 'Daily Summary',
      type: 'Summary',
      range: '15 Jul',
      generatedOn: '15 Jul 2026',
      user: 'System',
      status: 'Completed',
      badge: 'bg-success-subtle text-success',
      size: '950 KB'
    }

  ];
    // ======================================
  // Initialize Data
  // ======================================

  ngOnInit(): void {
    this.filteredReports = [...this.reports];
}

  // ======================================
  // Apply Filters
  // ======================================

  applyFilters(): void {

    this.filteredReports = this.reports.filter(report => {

      const typeMatch =
        this.selectedType === 'All Types' ||
        report.type === this.selectedType;

      const statusMatch =
        this.selectedStatus === 'All Status' ||
        report.status === this.selectedStatus;

      const userMatch =
        this.generatedBy === 'All Users' ||
        report.user === this.generatedBy;

      const searchMatch =
        this.searchText.trim() === '' ||
        report.name.toLowerCase().includes(this.searchText.toLowerCase()) ||
        report.type.toLowerCase().includes(this.searchText.toLowerCase()) ||
        report.user.toLowerCase().includes(this.searchText.toLowerCase());

      return typeMatch && statusMatch && userMatch && searchMatch;

    });

  }

  // ======================================
  // Reset Filters
  // ======================================

  resetFilters(): void {

    this.dateRange = '';
    this.selectedType = 'All Types';
    this.selectedStatus = 'All Status';
    this.generatedBy = 'All Users';
    this.searchText = '';

    this.filteredReports = [...this.reports];

  }
    // ======================================
  // Report Type Chart
  // ======================================

  createReportTypeChart(): void {

    new Chart('reportTypeChart', {

      type: 'doughnut',

      data: {

        labels: [
          'Reconciliation',
          'Audit',
          'Exception',
          'Compliance',
          'Summary'
        ],

        datasets: [
          {
            data: [45, 20, 12, 10, 13],

            backgroundColor: [
              '#2563EB',
              '#10B981',
              '#F59E0B',
              '#EF4444',
              '#7C3AED'
            ],

            borderWidth: 0
          }
        ]
      },

      options: {

        responsive: true,

        plugins: {

          legend: {
            position: 'bottom'
          }

        }

      }

    });

  }

  // ======================================
  // Status Chart
  // ======================================

  createStatusChart(): void {

    new Chart('statusChart', {

      type: 'doughnut',

      data: {

        labels: [
          'Completed',
          'In Progress',
          'Failed'
        ],

        datasets: [
          {
            data: [82, 12, 6],

            backgroundColor: [
              '#16A34A',
              '#F59E0B',
              '#EF4444'
            ],

            borderWidth: 0
          }
        ]
      },

      options: {

        responsive: true,

        plugins: {

          legend: {
            position: 'bottom'
          }

        }

      }

    });

  }

}